name: "Docker Images"
on:
  pull_request:
  push:
jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: [emulatorImage, devEnvironment]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Print nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

    - run: nix build .#docker.${{ matrix.image }}

    - run: cp ./result /tmp/${{ matrix.image }}.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.image }}
        path: /tmp/${{ matrix.image }}.tar

  # push-image:
  #   runs-on: ubuntu-latest
  #   environment: DockerHub
  #   needs: build-docker-image

  #   # if: ${{ github.ref == 'refs/heads/master' }}

  #   strategy:
  #     matrix:
  #       image: [emulatorImage] #, devEnvironment]

  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: ${{ matrix.image }}.tar
  #         path: /tmp

  #     - name: Log in to the Container registry
  #       uses: docker/login-action@v5
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - run: docker load --input /tmp/${{ matrix.image }}.tar

  #     - run: docker tag portal-emulator:latest afilini/test-push-github:latest
  #     - run: docker image push afilini/test-push-github:latest
